Repository FRONTENDSCHOOL7/final-14-Deskoration, pull requests merged in 2023-11, with the labels that each got.

#50 Feat#41_1 [마커 호버] 라우터 설정 & styled 파일 나누기
  src/App.js
  src/components/Ballon/Ballon.jsx
  src/components/Ballon/Ballon.styled.jsx
  src/pages/NewBoard/NewBoard.jsx
  src/pages/NewBoard/NewBoard.styled.jsx
  src/pages/NewBoard/PostUpload.jsx
  src/pages/NewBoard/PostUpload.styled.jsx
  src/pages/NewBoard/RegisterForm.jsx
  src/pages/User/Login.jsx
Labels: ♻️ 리팩토링, 🥸 구현 중..

#53 Feat#49_1 [API 추가] 이미지 api
  src/App.js
  src/hooks/img_Uploader.js
  src/pages/NewBoard/NewBoard.jsx
  src/pages/NewBoard/PostUpload.jsx
  src/router/PrivateRoute.jsx
  src/router/Router.jsx
  src/service/auth_service.jsx
  src/service/img_service.jsx
  src/service/post_service.jsx
Labels: ✨ 기능 추가, 🥸 구현 중..

#66 Feat#44_1 [Loading] 로딩화면 애니메이션
  src/assets/images/Loading.svg
  src/assets/images/bgLoading.jpg
  src/pages/Loading/Loading.jsx
  src/pages/Loading/Loading.styled.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#71 Feat#63_1 [게시글 작성] 오류 수정
  src/pages/NewBoard/PostUpload.jsx
  src/pages/NewBoard/RegisterForm.jsx
Labels: 🙏 PR 중..

#62 Feat#61_1 [theme 스타일] 컬러 변경
  src/components/GradientButton/GradientButton.styled.jsx
  src/components/Header/Header.styled.jsx
  src/pages/Chat/ChatListPage/ChatListPage.styled.jsx
  src/pages/Chat/ChatRoomPage/ChatRoomPage.styled.jsx
  src/styles/theme.js
Labels: 🙏 PR 중..

#73 Feat#36_2 [Input Component] placeholder, select 추가
  src/components/Input/Input.jsx
  src/components/Input/Input.styled.jsx
  src/pages/NewBoard/RegisterForm.jsx
  src/pages/Profile/ProfileUpload.jsx
  src/pages/User/Login.jsx
  src/pages/User/Signup.jsx
Labels: 🙏 PR 중..

#80 Feat#79_1 [Feed] 피드 페이지 UI 구현
  src/pages/Feed/Feed.jsx
  src/pages/Feed/Feed.styled.jsx
Labels: 🙏 PR 중..

#77 Feat#67_1 [게시글 상세보기] 게시글 이미지에 마커 보이게 구현
  src/pages/DetailPost/DetailPost.jsx
  src/pages/DetailPost/DetailPost.styled.jsx
  src/pages/Home/Article.jsx
  src/service/comment_service.jsx
  src/service/post_service.jsx
Labels: 🙏 PR 중.., ✨ 기능 추가, 🥸 구현 중..

#83 Feat#75_1 [라우터, 스타일] 라우터 및 전체 스타일 점검
  src/App.js
  src/Layout/DefaultLayout.jsx
  src/Layout/NoFooterLayout.jsx
  src/assets/images/Backward.svg
  src/assets/images/login/Facebook.png
  src/assets/images/login/Google.png
  src/assets/images/login/Kakao.png
  src/components/Footer/Buttons.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.styled.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.styled.jsx
  src/features/pageTitle/pageTitleSlice.js
  src/hooks/usePageHandler.js
  src/pages/Chat/ChatListPage/ChatListPage.jsx
  src/pages/Chat/ChatListPage/ChatListPage.styled.jsx
  src/pages/Chat/ChatRoomPage/ChatRoomPage.jsx
  src/pages/Chat/ChatRoomPage/ChatRoomPage.styled.jsx
  src/pages/DetailPost/DetailPost.jsx
  src/pages/DetailPost/DetailPost.styled.jsx
  src/pages/Feed/Feed.jsx
  src/pages/FollowFollowingList/FollowerList.jsx
  src/pages/FollowFollowingList/FollowerList.styled.jsx
  src/pages/Home/Article.jsx
  src/pages/Home/Article.styled.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/Slide.jsx
  src/pages/Home/Slide.styled.jsx
  src/pages/NewBoard/NewBoard.jsx
  src/pages/NewBoard/NewBoard.styled.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/Profile.styled.jsx
  src/pages/Profile/ProfileUpload.jsx
  src/pages/Profile/ProfileUpload.styled.jsx
  src/pages/Profile/UserProfile.jsx
  src/pages/Profile/UserProfile.styled.jsx
  src/pages/User/User.jsx
  src/pages/User/User.styled.jsx
  src/router/PublicRoute.jsx
  src/router/Router.jsx
  src/store.js
  src/styles/GlobalStyle.js
Labels: 🙏 PR 중..

#85 Feat#78_1 [상세보기] 게시글, 댓글 삭제
  src/App.js
  src/components/BottomSheet/BottomSheet.jsx
  src/components/BottomSheet/BottomSheet.styled.jsx
  src/pages/DetailPost/DetailPost.jsx
  src/pages/DetailPost/DetailPost.styled.jsx
  src/router/Router.jsx
  src/service/comment_service.jsx
  src/service/post_service.jsx
  src/styles/GlobalStyle.js
Labels: 🙏 PR 중.., ✨ 기능 추가

#96 Feat#91_1 [라우터] 리팩토링
  src/components/Footer/Buttons.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/pages/404/NotFoundPage.jsx
  src/pages/NewBoard/NewBoard.jsx
  src/pages/NewBoard/PostUploadForm.jsx
  src/pages/User/Login.jsx
  src/router/PrivateRoute.jsx
  src/router/PublicRoute.jsx
  src/router/Router.jsx
Labels: 🙏 PR 중.., ♻️ 리팩토링

#89 Feat#88_1 [로그아웃]
  src/components/BottomSheet/BottomSheet.jsx
  src/components/BottomSheet/BottomSheet.styled.jsx
  src/pages/Profile/Profile.jsx
Labels: ✨ 기능 추가

#100 Feat#92_1 [splash] splash와 홈화면 로딩 추가
  src/pages/Home/Article.jsx
  src/pages/Home/Home.jsx
  src/pages/Loading/CommonLoading.jsx
  src/pages/Loading/CommonLoading.styled.jsx
  src/pages/Loading/Splash.jsx
  src/pages/Loading/Splash.styled.jsx
  src/pages/User/User.jsx
Labels: 🙏 PR 중..

#99 Feat#82_1 [Api 코드 수정] 네이밍 변경 & 코드 통일
  src/components/Ballon/Ballon.jsx
  src/components/Header/Header.jsx
  src/components/Input/Input.jsx
  src/components/Marker/Marker.jsx
  src/pages/Chat/ChatListPage/ChatListPage.jsx
  src/pages/Chat/ChatRoomPage/ChatRoomPage.jsx
  src/pages/DetailPost/DetailPost.jsx
  src/pages/Feed/Feed.jsx
  src/pages/FollowFollowingList/FollowerList.jsx
  src/pages/FollowFollowingList/FollowingList.jsx
  src/pages/Home/Article.jsx
  src/pages/Home/Home.jsx
  src/pages/NewBoard/NewBoard.jsx
  src/pages/NewBoard/PostUploadForm.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileUpload.jsx
  src/pages/Profile/UserProfile.jsx
  src/pages/User/Login.jsx
  src/pages/User/Signup.jsx
  src/router/PrivateRoute.jsx
  src/router/PublicRoute.jsx
  src/router/Router.jsx
  src/service/auth_service.js
  src/service/auth_service.jsx
  src/service/base_url.js
  src/service/board_service.jsx
  src/service/comment_service.js
  src/service/comment_service.jsx
  src/service/follow_service.js
  src/service/follow_service.jsx
  src/service/img_service.js
  src/service/img_service.jsx
  src/service/post_service.js
  src/service/profile_service.js
  src/service/profile_service.jsx
Labels: 🙏 PR 중.., 🥸 구현 중.., 👌🏻 수정 중..

#102 Feat#101_1 [라우터] path name 변경
  src/components/Ballon/Ballon.jsx
  src/pages/Home/Home.jsx
  src/pages/NewBoard/NewBoard.jsx
  src/pages/NewBoard/RegisterForm.jsx
  src/pages/Profile/ProfileUpload.jsx
  src/pages/Profile/UserProfile.jsx
Labels: 🙏 PR 중.., ♻️ 리팩토링

#104 Feat#103_1 [말풍선] UI 변경
  src/components/Ballon/Ballon.styled.jsx
  src/pages/NewBoard/PostUploadForm.jsx
Labels: 🙏 PR 중.., ♻️ 리팩토링

#106 Feat#105_1 [로그인] 테스트 계정
  src/pages/User/Login.jsx
  src/pages/User/User.styled.jsx
Labels: 🙏 PR 중.., ✨ 기능 추가

#108 Feat#107_1 [detail post] 상품 보기
  src/components/Ballon/Ballon.jsx
  src/components/Input/Input.jsx
  src/components/Input/Input.styled.jsx
  src/components/Marker/Marker.jsx
  src/pages/DetailPost/DetailPost.jsx
  src/pages/NewBoard/NewBoard.jsx
  src/pages/NewBoard/RegisterForm.jsx
  src/router/Router.jsx
Labels: 🙏 PR 중.., ♻️ 리팩토링

#110 Feat#109_1 [Gradient Button] Add styled prop $
  src/components/BottomSheet/BottomSheet.jsx
  src/components/BottomSheet/BottomSheet.styled.jsx
  src/pages/Profile/Profile.jsx
Labels: 🙏 PR 중.., ♻️ 리팩토링

#128 Feat#126_1 [alert modal] 기능구현 및 적용
  src/components/AlertModal/AlertModal.jsx
  src/components/AlertModal/AlertModal.styled.jsx
  src/features/modal/alertModalSlice.js
  src/pages/NewBoard/PostUploadForm.jsx
  src/pages/User/Login.jsx
  src/pages/User/User.jsx
  src/pages/User/User.styled.jsx
  src/store.js
Labels: 🙆🏻‍♀️ 구현 완료, ✨ 기능 추가

#135 Feat/AddLike#133
  src/components/SocialButton/SocialButton.jsx
  src/components/SocialButton/SocialButton.styled.jsx
  src/pages/DetailPost/DetailPost.jsx
  src/pages/DetailPost/DetailPost.styled.jsx
  src/pages/Feed/Feed.jsx
  src/pages/Feed/Feed.styled.jsx
  src/service/like_service.js
Labels: 🙏 PR 중..

#152 Refactor/editFooterBtns#12
  src/components/Footer/Buttons.jsx
  src/components/Footer/Buttons.styled.jsx
  src/components/Footer/Footer.jsx
  src/pages/Feed/Feed.jsx
Labels: 🙏 PR 중.., ♻️ 리팩토링

#153 Feat/report#143[포스트,댓글]
  src/components/AlertModal/AlertModal.styled.jsx
  src/pages/DetailPost/DetailPost.jsx
  src/pages/DetailPost/DetailPost.styled.jsx
  src/pages/Feed/Feed.jsx
  src/service/comment_service.js
  src/service/post_service.js
Labels: 🙏 PR 중.., ✨ 기능 추가
