Repository FRONTENDSCHOOL7/final-14-Deskoration, pull requests merged in 2023-12, with the labels that each got.

#160 Refactor/detailPostItemUI#141
  src/assets/images/Share.svg
  src/components/Ballon/Ballon.jsx
  src/components/ShowProduct/ShowProduct.jsx
  src/components/ShowProduct/ShowProduct.styled.jsx
  src/router/Router.jsx
Labels: 🙏 PR 중.., ♻️ 리팩토링

#177 Refactor/userInputUpdate#179
  src/pages/User/Login.jsx
  src/pages/User/Signup.jsx
Labels: 🙏 PR 중..

#185 Feat/realTimeChat#173_3 [채팅목록]
  .gitignore
  src/firebase.js
  src/pages/Chat/ChatListPage/ChatListPage.jsx
  src/pages/Chat/ChatListPage/ChatListPage.styled.jsx
Labels: 🙏 PR 중..

#186 Feat#174_kakaoMapApi
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/assets/images/List.svg
  src/assets/images/MapPin.svg
  src/assets/images/SelectedMapPin.svg
  src/components/Ballon/Ballon.jsx
  src/components/ShowProduct/ShowProduct.jsx
  src/components/ShowProduct/ShowProduct.styled.jsx
  src/pages/NewBoard/AddMap/AddMap.jsx
  src/pages/NewBoard/AddMap/AddMap.styled.jsx
  src/pages/NewBoard/RegisterForm.jsx
  src/service/kakaoMap_service.js
Labels: 🙏 PR 중.., ✨ 기능 추가

#196 Refactor/applyRQtoFeed#193
  src/hooks/useLikeUpdate.js
  src/pages/Feed/Feed.jsx
  src/pages/Feed/Feed.styled.jsx
Labels: 🙏 PR 중..

#233 Refactor/axios#219
  package-lock.json
  package.json
  src/components/AlertModal/AlertModal.jsx
  src/components/PostDetail/Comment/Comment.jsx
  src/components/PostDetail/DetailPost/DetailPost.jsx
  src/hooks/useImgUpload.js
  src/hooks/useLikeUpdate.js
  src/pages/Chat/ChatListPage/ChatListPage.jsx
  src/pages/Chat/ChatRoomPage/ChatRoomPage.jsx
  src/pages/Feed/Feed.jsx
  src/pages/FollowFollowingList/FollowerList.jsx
  src/pages/FollowFollowingList/FollowingList.jsx
  src/pages/FollowFollowingList/UserFollowerList.jsx
  src/pages/FollowFollowingList/UserFollowingList.jsx
  src/pages/Home/Home.jsx
  src/pages/NewBoard/NewBoard.jsx
  src/pages/NewBoard/UpdateBoard.jsx
  src/pages/PostPage/DetailPostPage/DetailPostPage.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileUpload.jsx
  src/pages/Profile/UserProfile.jsx
  src/pages/User/Login.jsx
  src/pages/User/Signup.jsx
  src/pages/User/User.jsx
  src/router/PrivateRoute.jsx
  src/router/PublicRoute.jsx
  src/service/auth_service.js
  src/service/axiosInstance.js
  src/service/comment_service.js
  src/service/follow_service.js
  src/service/img_service.js
  src/service/like_service.js
  src/service/post_service.js
  src/service/profile_service.js
Labels: ✨ 기능 추가, ♻️ 리팩토링
